import type { VercelRequest, VercelResponse } from '@vercel/node';
import Stripe from 'stripe';
import { createClient } from '@supabase/supabase-js';

// Disable Vercel's automatic body parsing — Stripe needs the raw body
export const config = {
    api: { bodyParser: false },
};

// ─── Supabase admin client (bypasses RLS) ────────────────────
const supabase = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

// ─── Stripe client ────────────────────────────────────────────
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
    apiVersion: '2025-01-27.acacia',
});

// ─── Read raw body for signature verification ─────────────────
async function getRawBody(req: VercelRequest): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const chunks: Buffer[] = [];
        req.on('data', (chunk: Buffer) => chunks.push(chunk));
        req.on('end', () => resolve(Buffer.concat(chunks)));
        req.on('error', reject);
    });
}

// ─── Handler ──────────────────────────────────────────────────
export default async function handler(req: VercelRequest, res: VercelResponse) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    const signature = req.headers['stripe-signature'] as string;
    if (!signature) {
        return res.status(400).json({ error: 'Missing Stripe signature' });
    }

    let event: Stripe.Event;
    try {
        const rawBody = await getRawBody(req);
        event = stripe.webhooks.constructEvent(
            rawBody,
            signature,
            process.env.STRIPE_WEBHOOK_SECRET!,
        );
    } catch (err: any) {
        console.error('Webhook signature verification failed:', err.message);
        return res.status(400).json({ error: `Webhook error: ${err.message}` });
    }

    // ── Handle event types ────────────────────────────────────
    if (event.type === 'checkout.session.completed') {
        const session = event.data.object as Stripe.Checkout.Session;
        await handleCheckoutCompleted(session);
    }

    if (event.type === 'checkout.session.expired') {
        const session = event.data.object as Stripe.Checkout.Session;
        const orderId = session.metadata?.order_id;
        if (orderId) {
            await supabase
                .from('orders')
                .update({ status: 'cancelled' })
                .eq('id', orderId);
        }
    }

    return res.status(200).json({ received: true });
}

// ─── checkout.session.completed ──────────────────────────────
async function handleCheckoutCompleted(session: Stripe.Checkout.Session) {
    const {
        order_id,
        user_id,
        event_id,
        ticket_type_id,
        voucher_id,
        discount_applied,
        attendee_name,
        attendee_email,
        attendee_phone,
        attendee_company,
        attendee_job_title,
    } = session.metadata ?? {};

    if (!order_id || !user_id) {
        console.error('Missing metadata in session:', session.id);
        return;
    }

    // 1. Update order → paid
    const { error: orderErr } = await supabase
        .from('orders')
        .update({
            status: 'paid',
            stripe_session_id: session.id,
            updated_at: new Date().toISOString(),
        })
        .eq('id', order_id);

    if (orderErr) {
        console.error('Failed to update order:', orderErr);
        return;
    }

    // 2. Create attendee record (idempotent via upsert)
    const { data: attendee, error: attendeeErr } = await supabase
        .from('attendees')
        .upsert(
            {
                user_id,
                event_id,
                order_id,
                ticket_type_id,
                name: attendee_name ?? attendee_email ?? 'Unknown',
                email: attendee_email ?? '',
                phone: attendee_phone || null,
                company: attendee_company || null,
                job_title: attendee_job_title || null,
                checkin_status: 'pending',
                consent: true,
                // qr_code_value auto-generated by DB default
            },
            { onConflict: 'order_id', ignoreDuplicates: true },
        )
        .select()
        .single();

    if (attendeeErr) {
        console.error('Failed to create attendee:', attendeeErr);
        // Don't return — still try to handle voucher
    }

    // 3. Handle voucher redemption
    if (voucher_id && Number(discount_applied) > 0) {
        // Increment uses_count
        await supabase.rpc('increment_voucher_uses', { voucher_uuid: voucher_id });

        // Log redemption
        if (attendee?.id) {
            await supabase.from('voucher_redemptions').insert({
                voucher_id,
                user_id,
                order_id,
                attendee_id: attendee.id,
                discount_applied: Number(discount_applied),
            });
        }
    }
}
